-- Additive and repeatable. Existing family_links rows are kept intact.
CREATE TABLE IF NOT EXISTS family_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  parent_line_user_id text NOT NULL UNIQUE,
  child_line_user_id text NOT NULL UNIQUE
);
ALTER TABLE family_links ADD COLUMN IF NOT EXISTS revoked_at timestamptz;
-- Stop with a safe error if legacy/manual data puts one person in two roles.
DO $$ BEGIN
  IF EXISTS (SELECT member FROM (
    SELECT parent_line_user_id AS member FROM family_links WHERE revoked_at IS NULL
    UNION ALL SELECT child_line_user_id FROM family_links WHERE revoked_at IS NULL
  ) members GROUP BY member HAVING count(*)>1) THEN
    RAISE EXCEPTION 'family_membership_conflict_requires_review';
  END IF;
END $$;
-- Retain revoked relationships for a 30-day deletion grace period.
-- Active relationships remain unique. The worker also prevents cross-role reuse.
DO $$ DECLARE item record; BEGIN
  FOR item IN SELECT conname FROM pg_constraint WHERE conrelid='family_links'::regclass AND contype='u'
    AND pg_get_constraintdef(oid) IN ('UNIQUE (parent_line_user_id)','UNIQUE (child_line_user_id)')
  LOOP EXECUTE format('ALTER TABLE family_links DROP CONSTRAINT %I',item.conname); END LOOP;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS family_active_parent ON family_links(parent_line_user_id) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS family_active_child ON family_links(child_line_user_id) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS care_profiles (
  family_id bigint PRIMARY KEY REFERENCES family_links(id) ON DELETE CASCADE,
  nickname text NOT NULL DEFAULT '',
  chat_style text NOT NULL DEFAULT '',
  topics text[] NOT NULL DEFAULT '{}',
  interests text[] NOT NULL DEFAULT '{}',
  background text[] NOT NULL DEFAULT '{}',
  avoid_topics text[] NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS care_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id bigint NOT NULL REFERENCES family_links(id) ON DELETE CASCADE,
  topic text NOT NULL CHECK (length(topic) BETWEEN 1 AND 200),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','asked','answered','cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT now() + interval '7 days',
  asked_at timestamptz,
  answered_at timestamptz
);
CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id bigint NOT NULL REFERENCES family_links(id) ON DELETE CASCADE,
  speaker text NOT NULL CHECK (speaker IN ('parent','assistant')),
  message text NOT NULL CHECK (length(message) <= 2000),
  event_id text NOT NULL,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  UNIQUE(event_id,speaker)
);
CREATE INDEX IF NOT EXISTS messages_context ON messages(family_id,created_at DESC);
CREATE INDEX IF NOT EXISTS messages_expiry ON messages(expires_at);
CREATE TABLE IF NOT EXISTS radar_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id bigint NOT NULL REFERENCES family_links(id) ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN ('sleep','physical','mood','daily','safety')),
  level text NOT NULL CHECK (level IN ('green','yellow','red')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
  first_seen timestamptz NOT NULL,
  last_seen timestamptz NOT NULL,
  signal_days text[] NOT NULL DEFAULT '{}',
  occurrences integer NOT NULL DEFAULT 1,
  reported_days integer NOT NULL DEFAULT 0,
  reason text NOT NULL,
  last_notified_at timestamptz,
  last_notified_level text,
  expires_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS radar_open_category ON radar_events(family_id,category) WHERE status='open';
CREATE TABLE IF NOT EXISTS pairing_requests (
  code text PRIMARY KEY CHECK (code ~ '^[0-9]{6}$'),
  parent_id text NOT NULL UNIQUE,
  child_id text,
  expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS pairing_limits (
  actor_hash text PRIMARY KEY,
  window_start timestamptz NOT NULL,
  attempts integer NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS ai_usage (
  day date PRIMARY KEY,
  calls integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS webhook_inbox (
  event_id text PRIMARY KEY,
  source_id text,
  payload jsonb,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','failed')),
  received_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT now() + interval '7 days',
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbox_pending ON webhook_inbox(received_at) WHERE status='pending';
CREATE TABLE IF NOT EXISTS notification_outbox (
  id uuid PRIMARY KEY,
  family_id bigint REFERENCES family_links(id) ON DELETE CASCADE,
  radar_id bigint REFERENCES radar_events(id) ON DELETE CASCADE,
  event_id text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('reply','push')),
  destination text,
  content text,
  level text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed','cancelled')),
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  sent_at timestamptz,
  UNIQUE(event_id,kind,destination)
);
CREATE INDEX IF NOT EXISTS outbox_pending ON notification_outbox(next_attempt_at) WHERE status='pending';
-- No browser/Data API access to family data. Server uses DATABASE_URL only.
ALTER TABLE family_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE care_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE care_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE radar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE pairing_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE pairing_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_outbox ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
    REVOKE ALL ON family_links,care_profiles,care_tasks,messages,radar_events,pairing_requests,pairing_limits,ai_usage,webhook_inbox,notification_outbox FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL ON family_links,care_profiles,care_tasks,messages,radar_events,pairing_requests,pairing_limits,ai_usage,webhook_inbox,notification_outbox FROM authenticated;
  END IF;
END $$;
